/*
* DATASET Geo Locations
*/
var silkRoadCities = [
	{ name: 'Istanbul, Turkey', geo: '41.00527,28.97696'},
//			{ name: 'Bursa, Turkey', geo: '40.266864,29.063448'},
//			{ name: 'Beypazari, Turkey', geo: '40.1675,31.921111'},
	{ name: 'Mudurnu, Turkey', geo: '40.46931,31.20969'},
//			{ name: 'Tarakli, Turkey', geo: '40.396944,30.492778'},
	{ name: 'Konya, Turkey', geo: '37.866667,32.483333'},
	{ name: 'Adana, Turkey', geo: '37,35.321333'},
	{ name: 'Antioch, Turkey', geo: '36.202809,36.160299'},
//			{ name: 'Gaziantep, Turkey', geo: '37.06622,37.38332'},
//			{ name: 'Trabzon, Turkey', geo: '41.00145,39.7178'},
	{ name: 'Tyre, Lebanon', geo: '33.272157,35.203278'},
//			{ name: 'Aleppo, Syria', geo: '36.215549,37.159279'},
//			{ name: 'Tartus, Syria', geo: '34.883333,35.883333'},
//			{ name: 'Homs, Syria', geo: '34.733879,36.71817'},
	{ name: 'Damascus, Syria', geo: '33.5111,36.3064'},
	{ name: 'Palmyra, Syria', geo: '34.547951,38.278671'},
//			{ name: 'Ar-Raqqah, Syria', geo: '35.947449,39.036781'},
	{ name: 'Dura Europos, Syria', geo: '34.74872,40.729797'},
//			{ name: 'Samarra, Iraq', geo: '34.19421,43.874931'},
//			{ name: 'Fallujah, Iraq', geo: '33.35,43.783333'},
	{ name: 'Baghdad, Iraq', geo: '33.325,44.422'},
//			{ name: 'Ctesiphon, Iraq', geo: '33.093614,44.581081'},
//			{ name: 'Baquba, Iraq', geo: '33.75,44.633333'},
	{ name: 'Kermanshah, Iran', geo: '34.314167,47.065'},
	{ name: 'Hamadan, Iran', geo: '34.8,48.516667'},
	{ name: 'Tehran, Iran', geo: '35.696216,51.422945'},
	{ name: 'Damghan, Iran', geo: '36.168333,54.348056'},
	{ name: 'Sabzevar, Iran', geo: '36.213718,57.670979'},
	{ name: 'Nishapur, Iran', geo: '36.213333,58.795833'},
//			{ name: 'Mashhad, Iran', geo: '36.3,59.6'},
//			{ name: 'Tus, Iran', geo: '36.479844,59.509517'},
//			{ name: 'Yazd, Iran', geo: '31.89661,54.36068'},
//			{ name: 'Bam, Iran', geo: '29.106111,58.356944'},
	{ name: 'Herat, Afghanistan', geo: '34.341944,62.203056'},
//			{ name: 'Kandahar, Afghanistan', geo: '31.61088,65.700272'},
//			{ name: 'Bamyan, Afghanistan', geo: '34.90733,67.189449'},
//			{ name: 'Kabul, Afghanistan', geo: '34.528455,69.171703'},
//			{ name: 'Nisa, Turkmenistan', geo: '37.951348,58.211364'},
//			{ name: 'Merv, Turkmenistan', geo: '37.6,61.833333'},
//			{ name: 'Urgench, Turkmenistan', geo: '41.55386,60.621769'},
	{ name: 'Amul, Turkmenistan', geo: '39.083333,63.566667'},
	{ name: 'Bukhara, Uzbekistan', geo: '39.765869,64.422348'},
//			{ name: 'Shahrisabz, Uzbekistan', geo: '39.05547,66.826157'},
	{ name: 'Samarkand, Uzbekistan', geo: '39.657581,66.947601'},
//			{ name: 'Tashkent, Uzbekistan', geo: '41.266667,69.216667'},
	{ name: 'Khujand, Tajikistan', geo: '40.283333,69.633333'},
//			{ name: 'Istaravshan, Tajikistan', geo: '39.908401,69.005127'},
	{ name: 'Taraz, Kazakhstan', geo: '42.9,71.366667'},
//			{ name: 'Hazrat-e Turkestan, Kazakhstan', geo: '43.294701,68.258537'},
//			{ name: 'Almaty, Kazakhstan', geo: '43.255058,76.912628'},
	{ name: 'Kyrgyzstan, Kyrgyzstan', geo: '41.20438,74.766098'},
//			{ name: 'Quetta, Pakistan', geo: '30.209459,67.018173'},

	{ name: 'Peshawar, Pakistan', geo: '34.004299,71.54483'},
	{ name: 'Taxila, Pakistan', geo: '33.747486,72.810189'},
//			{ name: 'Multan, Pakistan', geo: '30.190189,71.458023'},
//			{ name: 'Banbhore, Pakistan', geo: '24.77035,67.525749'},
//			{ name: 'Thatta, Pakistan', geo: '24.74798,67.923897'},
//			{ name: 'Leh, India', geo: '34.152586,77.577054'},
	{ name: 'Jaisalmer, India', geo: '26.915749,70.908344'},
	{ name: 'Mathura, India', geo: '27.492413,77.673673'},
//			{ name: 'Varanasi, India', geo: '25.317645,82.973914'},
//			{ name: 'Pataliputra, India', geo: '25.61046,85.141667'},
	{ name: 'Kathmandu, Nepal', geo: '27.7,85.333333'},
//			{ name: 'Lhasa, Tibet', geo: '29.645554,91.140856'},
//			{ name: 'Qing Wa Da Zi Lu, Tibet', geo: '29.028618,91.687003'},
//			{ name: 'Narsingdi, Bangladesh', geo: '23.919267,90.717649'},
	{ name: 'Mahasthangarh Museum, Bangladesh', geo: '24.962488,89.344334'},
//			{ name: 'Munshiganj, Bangladesh', geo: '23.524869,90.337189'},
	{ name: 'Somapura, Bangladesh', geo: '25.030864,88.976986'},
	{ name: 'Bhitagarh, Bangladesh', geo: '25.413974,88.528948'},
	{ name: 'Sonargaon, Bangladesh', geo: '23.646095,90.599104'},
	{ name: 'Chittagong Division, Bangladesh', geo: '22.330391,91.82518'},
//			{ name: 'Comilla, Bangladesh', geo: '23.455959,91.182037'},
	{ name: 'Jahangir Nagar, Bangladesh', geo: '23.709921,90.407143'},
	{ name: 'Jakar, Bhutan', geo: '27.565239,90.739025'},

	{ name: 'Kashgar, China', geo: '39.4704,75.989755'},
//			{ name: 'Aksu, China', geo: '41.168779,80.260605'},
//			{ name: 'Kucha, China', geo: '41.717906,82.962016'},
//			{ name: 'Korla, China', geo: '41.72664,86.17401'},
//			{ name: 'Loulan, China', geo: '42.861922,90.216197'},
//			{ name: 'Karasahr, China', geo: '42.062255,86.570957'},
//			{ name: 'Turpan, China', geo: '42.942328,89.185877'},
//			{ name: 'Jiaohe Ruins, China', geo: '42.953244,89.066056'},
//			{ name: 'Turpan Water Museum, China', geo: '42.951384,89.189655'},
//			{ name: 'Gaochang, China', geo: '43.753182,87.458609'},
//			{ name: 'Bezeklik Thousand Buddha Caves, China', geo: '42.956783,89.541191'},
//			{ name: 'Kumul, China', geo: '42.818501,93.514917'},
//			{ name: 'Urumqi, China', geo: '43.825645,87.616823'},
	{ name: 'Pishan, China', geo: '37.62145,78.283669'},
	{ name: 'Hotan, China', geo: '37.114157,79.922211'},
	{ name: 'Niya, China', geo: '37.06408,82.695862'},
	{ name: 'Ruoqiang Town, China', geo: '39.019226,88.168967'},
//			{ name: 'Miran, China', geo: '31.602013,74.358402'},
//			{ name: 'Mogao Caves, China', geo: '22.530727,113.990164'},
//			{ name: 'Yangguan, China', geo: '23.020536,113.751765'},
//			{ name: 'Anxi, China', geo: '25.055999,118.186264'},
//			{ name: 'Dunhuang, China', geo: '40.14213,94.661881'},
//			{ name: 'Jiayuguan, China', geo: '39.77313,98.289152'},
//			{ name: 'Jiuquan, China', geo: '39.732488,98.494411'},
//			{ name: 'Zhangye, China', geo: '38.925646,100.449822'},
//			{ name: 'Shandan, China', geo: '38.784675,101.088572'},
//			{ name: 'Liqian, China', geo: '38.196455,101.871348'},
//			{ name: 'Liangzhou, China', geo: '37.928323,102.642039'},
//			{ name: 'Tianzhu, China', geo: '36.971812,103.14182'},
//			{ name: 'Lanzhou, China', geo: '36.061255,103.834377'},
//			{ name: 'Tianshui, China', geo: '34.580864,105.724947'},
	{ name: 'Baoji, China', geo: '34.36198,107.237974'},
	{ name: 'Xian, China', geo: '34.341568,108.940175'},
	{ name: 'Yumen Pass, China', geo: '35.61325,110.558125'}
//			{ name: 'Pyongyang, Korea', geo: '38.961343,125.827996'},
//			{ name: 'Gyeongju, Korea', geo: '35.856172,129.224748'},
//			{ name: 'Nara, Japan', geo: '34.685087,135.805'},
];

function lookupCountryDescription(country){
	return lookupCountry(country).description;
}

function lookupCountry(country){
	for (var j = 0; j < descriptionCountries.length; j++){
		if (country.split(",")[1].replace(/^\s+|\s+$/g, '') == descriptionCountries[j].name) return descriptionCountries[j];
	}
}

var descriptionCountries = [
	{name: 'China', 
		fullName: "People's Republic of China", 
		description: "China is the fastest-growing free market economy on the planet but social reforms lag far behind economic changes. The Government still tries to control religious practice, requiring all religious groups to register. Even state-sanctioned churches are closely monitored. All other churches are regarded as 'illegal' and are often branded 'evil cults', forcing some underground. A number of Christians have been detained longer term, while more than 100 are arrested or interrogated each year.",
		fullDescription: "China is the fastest-growing free market economy on the planet but social reforms lag far behind economic changes. The Government still tries to control religious practice, requiring all religious groups to register. Even state-sanctioned churches are closely monitored. All other churches are regarded as 'illegal' and are often branded 'evil cults', forcing some underground. A number of Christians have been detained longer term, while more than 100 are arrested or interrogated each year. <br><br> In recent years, China has attempted to silence its critics by passing laws purporting to show its commitment to religious freedom. However, official documents leaked to the international media - and ongoing detentions - suggest the Government is continuing to clamp down on unregistered groups, particularly house churches.",
		capital: "Beijing",
		government: "Communist state, Socialist state, Single-party state",
		values: [44.3, 12.5, 7.9, 4.5, 28.5, 2.3],
		labels: ["Non-religious", "Buddhist", "Christian", "Ethno Religionist", "Chinese Universalist", "Other"],
		population: "over 1.35 billion",
		sources: "(Sources: BBC; China Aid; International Christian Concern; Operation World 2010; Release International; The World Factbook 2013; Wikipedia. Image Sources: http://sxc.hu and http://flickr.com.)"},
	{name: 'Tajikistan', 
		fullName: "Republic of Tajikistan", 
		description: "Immediately after Tajikistan gained independence from the Soviet Union in 1991, it was plunged into a five-year civil war for control of Parliament between the Moscow-backed government and the Islamist-led opposition. Fear of militant Islam continues to inform government policy and religious practice is monitored closely.",
		fullDescription: "Immediately after Tajikistan gained independence from the Soviet Union in 1991, it was plunged into a five-year civil war for control of Parliament between the Moscow-backed government and the Islamist-led opposition. Fear of militant Islam continues to inform government policy and religious practice is monitored closely. <br><br> Religious freedom has diminished since 2009, when the Government restated the primacy of Sunni Islam in Tajik life and introduced a new Religion Law. Though the restrictions in this law mainly affect Muslims, they also single out religious minorities with a perceived 'foreign influence', such as Christianity. All unregistered religious activity is now illegal. All previously registered religious organisations have had to re-register; some have been refused registration and others face a long wait for their application to be processed.",
		capital: "Dushanbe",
		government: "Republic",
		values: [93.9, 5, 1, 0.1],
		labels: ["Muslim", "Non-religious", "Christian", "Other"],
		population: "7.9 million",
		sources: "(Sources: BBC; Forum 18; International Christian Concern; Operation World 2010; Release International; The World Factbook 2013; Wikipedia. Image Sources: http://sxc.hu and http://flickr.com.)"},
	{name: 'Kyrgyzstan', 
		fullName: "Kyrgyz Republic", 
		description: "Kyrgyzstan's Government is secular but the country has implemented harsh laws that restrict religious liberties for Christians and other minorities. Under legislation that came into force in 2009, a church must have 200 members before it can be officially registered - otherwise it is deemed illegal. Previously, a church was required to have just ten members to be 'legal'. No Protestant or Catholic congregation has gained registration since the repressive Religion Law came into force in January 2009.",
		fullDescription: "Kyrgyzstan's Government is secular but the country has implemented harsh laws that restrict religious liberties for Christians and other minorities. Under legislation that came into force in 2009, a church must have 200 members before it can be officially registered - otherwise it is deemed illegal. Previously, a church was required to have just ten members to be 'legal'. No Protestant or Catholic congregation has gained registration since the repressive Religion Law came into force in January 2009. <br><br> Christians are not allowed to worship in houses or public locations, only in designated church buildings. There is a ban on distributing evangelistic literature, including Bibles, in the country. Kyrgyzstan became Central Asia's first parliamentary democracy in 2010, prompting hopes of reform and greater religious liberty. These hopes have yet to be realised. The Government remains concerned about the growth of jihadist groups such as Hizb-ut Tahrir.",
		capital: "Bishkek",
		government: "Republic",
		values: [88.7, 5.3, 5.3, 0.7],
		labels: ["Muslim", "Non-religious", "Christian", "Other"],
		population: "5.5 million",
		sources: "(Sources: BBC; Forum 18, International Christian Concern, Operation World 2010; The World Factbook 2013, VOM Canada; Wikipedia. Image Sources: http://sxc.hu and http://flickr.com.)"},
	{name: 'Kazakhstan', 
		fullName: "Republic of Kazakhstan", 
		description: "Kazakhstan's independence from the Soviet Union led to a revival of interest in traditional Islam, now the dominant religion. The church too has grown since 1991. Yet, fear of Islamist extremism prompted the Government to approve restrictive religious laws in 2011. The laws ban prayer rooms in state buildings and require all missionaries to register with the authorities every year.",
		fullDescription: "Kazakhstan's independence from the Soviet Union led to a revival of interest in traditional Islam, now the dominant religion. The church too has grown since 1991. Yet, fear of Islamist extremism prompted the Government to approve restrictive religious laws in 2011. The laws ban prayer rooms in state buildings and require all missionaries to register with the authorities every year. <br><br> These religious laws have also been used to limit, restrict and even persecute Christians, particularly newer and more active groups. Evangelicals, for example, are often regarded as dangerous sects and some Kazakhs still link Christianity with imperial Russia. Smaller Christian gatherings, including house churches, have been raided by secret police. Observers such as Forum 18 continue to document 'serious violations' of religious liberties.",
		capital: "Astana",
		government: "Republic but with authoritarian presidential rule",
		values: [53.6, 12.2, 33.9 , 0.3],
		labels: ["Muslim", "Christian", "Non-religious", "Other"],
		population: "17.7 million",
		sources: "(Sources: BBC; Forum 18, International Christian Concern, Operation World 2010; The World Factbook 2013, VOM Canada; Wikipedia. Image Sources: http://sxc.hu and http://flickr.com.)"},
	{name: 'Uzbekistan', 
		fullName: "Republic of Uzbekistan", 
		description: "All religious communities in Uzbekistan are required to register with the authorities - but only approved groups can register. These include some Muslim groups, Jews, the Russian Orthodox Church and a few Protestant churches. Registration is often delayed or refused. Even registered churches have been raided - and even closed down immediately if they were not able to produce their registration papers at once. Evangelism, missionary activity and religious instruction are banned, as are religious meetings held in private homes.",
		fullDescription: "All religious communities in Uzbekistan are required to register with the authorities - but only approved groups can register. These include some Muslim groups, Jews, the Russian Orthodox Church and a few Protestant churches. Registration is often delayed or refused. Even registered churches have been raided - and even closed down immediately if they were not able to produce their registration papers at once. Evangelism, missionary activity and religious instruction are banned, as are religious meetings held in private homes. <br><br> Unregistered groups are illegal and face fines, confiscation of property, imprisonment, and other types of persecution. Christians' homes and churches continue to be raided and many believers have been fined for sharing their faith, holding religious services and owning Christian literature. Earlier this year, a 76-year-old woman with Parkinson's disease had her home in Guliston near Tashkent raided during the night under the guise of 'anti-terror cleaning'; she was fined ten times the average monthly wage.",
		capital: "Tashkent",
		government: "Republic but with authoritarian presidential rule",
		values: [84.9, 0.7, 13.8, 0.2, 0.4],
		labels: ["Muslim", "Christian", "Non-religious", "Ethno Religionist", "Other"],
		population: "28.6 million",
		sources: "(Sources: BBC; Forum 18; International Christian Concern; Operation World 2010; Release International; The World Factbook 2013; Wikipedia. Image Sources: http://sxc.hu and http://flickr.com.)"},
	{name: 'India', 
		fullName: "Republic of India", 
		description: "India is the world's largest democracy and a growing economic powerhouse - yet, for its Christians, life is increasingly insecure. The rise of Hindutva extremism, which advocates the expulsion of non-Hindus from India, sparked a hate campaign against Christians in the late-1990s which has since gathered pace.",
		fullDescription: "India is the world's largest democracy and a growing economic powerhouse - yet, for its Christians, life is increasingly insecure. The rise of Hindutva extremism, which advocates the expulsion of non-Hindus from India, sparked a hate campaign against Christians in the late-1990s which has since gathered pace. <br><br> Release partners say that persecution of Christians is particularly intense in Andhra Pradesh and Karnataka states in the south. Pastors of independent churches in rural places - a significant area for church growth - are a particular target. However, Christians in other states have also been targeted, most notably in Odisha (formerly Orissa) where about 120 Christians were killed and more than 50,000 displaced in 2008 in a wave of anti-Christian violence.",
		capital: "New Delhi",
		government: "Federal republic",
		values: [74.3, 3.9, 14.2, 5.8, 1.8],
		labels: ["Hindu", "Other", "Muslim", "Christian", "Sikh"],
		population: "1.2 billion",
		sources: "(Sources: AICC; International Christian Concern; Operation World 2010; Release International; The World Factbook 2013; Christian Today; AsiaNews; Wikipedia. Image Sources: http://sxc.hu and http://flickr.com.)"
		},
	{name: 'Pakistan', 
		fullName: "Islamic Republic of Pakistan", 
		description: "Christians are among the poorest and most marginalised in Pakistani society, widely discriminated against in employment, education and the judicial system. For example, Pakistan's blasphemy laws - especially Section 295C of the Penal Code - are frequently used against religious minorities such as Christians sometimes to settle personal scores. The number of Christians charged is disproportionately high.",
		fullDescription: "Christians are among the poorest and most marginalised in Pakistani society, widely discriminated against in employment, education and the judicial system. For example, Pakistan's blasphemy laws - especially Section 295C of the Penal Code - are frequently used against religious minorities such as Christians sometimes to settle personal scores. The number of Christians charged is disproportionately high. <br><br> Meanwhile, radical Islam is spreading. Islamic extremists have gained popular support by providing hospitals, job training, universities - and Islamic schools or madrassas. The Government faces criticism for trying to appease Islamic hardliners and not doing enough to protect Christian communities. So Christians remain a frequent target for violence. Several Christian areas in Punjab were raided by extremists earlier this year, following accusations of blasphemy. Police are accused of apathy - or even complicity - in such attacks.",
		capital: "Islamabad",
		government: "Federal republic",
		values: [95.8, 2.4, 1.6, 0.2],
		labels: ["Muslim", "Christian", "Hindu", "Other"],
		population: "193.2 million",
		sources: "(Sources: BBC; International Christian Concern; Operation World 2010; Release International; The World Factbook 2013; Worldwatch Monitor; Reuters; Wikipedia. Image Sources: http://sxc.hu and http://flickr.com.)"},
	{name: 'Afghanistan', 
		fullName: "Islamic Republic of Afghanistan", 
		description: "Persecution of non-Muslims was blatant and legally enforced through Sharia (Islamic law) under the Taliban. They were toppled by the US-led invasion of the country in 2001 and Afghanistan now has a transitional Government and a new constitution. Yet, the situation for the country's tiny Christian community is much the same.",
		fullDescription: "Persecution of non-Muslims was blatant and legally enforced through Sharia (Islamic law) under the Taliban. They were toppled by the US-led invasion of the country in 2001 and Afghanistan now has a transitional Government and a new constitution. Yet, the situation for the country's tiny Christian community is much the same. <br><br> Even though the law does not discriminate against Christians, it turns a blind eye when persecution occurs and conversion from Islam is still widely considered as apostasy. Christians with a Muslim background face discrimination, even violence. Most meet in homes, usually in secret. Afghan Christians are concerned about the implications for religious liberties when coalition forces withdraw in 2014.",
		capital: "Kabul",
		government: "Islamic republic",
		values: [99.8, 0.07, 0.05, 0.08],
		labels: ["Muslim", "Non-religious", "Christian", "Other"],
		population: "31.1 million",
		sources: "(Sources: BBC; International Christian Concern; Operation World 2010; Release International; The World Factbook 2013; Wikipedia. Image Sources: http://sxc.hu and http://flickr.com.)"},
	{name: 'Turkmenistan', 
		fullName: "Turkmenia", 
		description: "Freedom of religion or belief is highly restricted in Turkmenistan. Its restrictive laws permit only two religious communities to register: the Sunni Muslim Board and the Russian Orthodox Church. It is impossible to build a place of worship if you belong to an unrecognised group, such as a Protestant church. Even registered groups face restrictions on having a place of worship and risk being raided. It is illegal to print and import religious literature.",
		fullDescription: "Freedom of religion or belief is highly restricted in Turkmenistan. Its restrictive laws permit only two religious communities to register: the Sunni Muslim Board and the Russian Orthodox Church. It is impossible to build a place of worship if you belong to an unrecognised group, such as a Protestant church. Even registered groups face restrictions on having a place of worship and risk being raided. It is illegal to print and import religious literature. <br><br> In 2007, it seemed that the authorities were mounting a concerted crackdown on Christians - one that has continued ever since. The authorities have accused Christians of 'conducting criminal activity and political activity against the Government', adding that the Government would do 'whatever it took to crush and destroy them'.",
		capital: "Ashgabat",
		government: "Republic but with authoritarian presidential rule",
		values: [96.1, 2, 1.8, 0.1],
		labels: ["Muslim", "Non-religious", "Christian", "Other"],
		population: "5.1 million",
		sources: "(Sources: BBC; International Christian Concern; Forum 18; Operation World 2010; Release International; The World Factbook 2013; Mission Network News; Wikipedia. Image Sources: http://sxc.hu and http://flickr.com.)"},
	{name: 'Iran', 
		fullName: "Islamic Republic of Iran", 
		description: "A theocratic Shia Government has held sway in Iran since the overthrow of the monarchy in 1979. Hardline clerics wield political control, under the authority of the Supreme Leader, the Ayatollah. Freedom for all faiths other than Shia Islam is limited, despite constitutional guarantees of religious liberty. Evangelising Muslims is still banned and the official penalty for apostasy (conversion from Islam) is death, although the sentence is rarely carried out.",
		fullDescription: "A theocratic Shia Government has held sway in Iran since the overthrow of the monarchy in 1979. Hardline clerics wield political control, under the authority of the Supreme Leader, the Ayatollah. Freedom for all faiths other than Shia Islam is limited, despite constitutional guarantees of religious liberty. Evangelising Muslims is still banned and the official penalty for apostasy (conversion from Islam) is death, although the sentence is rarely carried out. <br><br> Release contacts say that ordinary Christians who keep a low profile are able to practise their faith quietly, without too much interference. More prominent believers such as pastors are increasingly hard-pressed; indeed, several are currently in jail for their faith. Christians with a Muslim background are a particular target for persecution.",
		capital: "Tehran",
		government: "Theocratic republic",
		values: [98.6, 0.5, 0.4, 0.5],
		labels: ["Muslim", "Christian", "Baha'", "Other"],
		population: "79.8 million",
		sources: "(Sources: BBC; International Christian Concern; Operation World 2010; Release International; The World Factbook 2013; Middle East Concern; Wikipedia. Image Sources: http://sxc.hu and http://flickr.com.)"
		},
	{name: 'Azerbaijan', 
		fullName: "Republic of Azerbaijan", 
		description: "Freedom of religion remains highly restricted in Azerbaijan. All gatherings for worship must be reported to the Government and churches must be officially registered. However, registration can take years and some denominations are routinely denied it. Christian activity is monitored by the secret service. Officials have raided Christian meetings held in homes or other non-registered locations, confiscating Christian literature and imposing stiff fines on pastors.",
		fullDescription: "Freedom of religion remains highly restricted in Azerbaijan. All gatherings for worship must be reported to the Government and churches must be officially registered. However, registration can take years and some denominations are routinely denied it. Christian activity is monitored by the secret service. Officials have raided Christian meetings held in homes or other non-registered locations, confiscating Christian literature and imposing stiff fines on pastors. <br><br> Restrictions on religious liberties are compounded by racial discrimination: the Christian population is almost entirely ethnic Armenian and Russian, while the Muslim population is largely ethnic Azeri.  Christians are often viewed as traitors loyal to Azerbaijan's rival Christian neighbour, Armenia, so can face difficulties in securing and keeping employment.",
		capital: "Baku",
		government: "Republic",
		values: [87.6, 2.7, 9.6, 0.1],
		labels: ["Muslim", "Non-religious", "Christian", "Other"],
		population: "9.5 million",
		sources: "(Sources: Forum 18, International Christian Concern, Operation World 2010; The World Factbook 2013, VOM Canada; Release contacts; Wikipedia. Image Sources: http://sxc.hu and http://flickr.com.)"
		},
	{name: 'Iraq', 
		fullName: "Republic of Iraq", 
		description: "Sporadic violence continues in Iraq and the political situation remains unstable, as different factions (both political and religious) vie for power. Islamist militant groups continue to target Christians directly. The vast majority of Christians displaced by violence within Iraq in recent years have gone to the north, to cities such as Nineveh and Mosul. Yet, there too they have faced violence from insurgents and extremists.",
		fullDescription: "Sporadic violence continues in Iraq and the political situation remains unstable, as different factions (both political and religious) vie for power. Islamist militant groups continue to target Christians directly. The vast majority of Christians displaced by violence within Iraq in recent years have gone to the north, to cities such as Nineveh and Mosul. Yet, there too they have faced violence from insurgents and extremists. <br><br> While the Government has publicly condemned violence against minority groups, it continues to fall short in offering them protection or bringing culprits to justice. Only half the Iraqi Christian community as it existed before the US-led invasion in 2003 is believed to remain in the country.",
		capital: "Baghdad",
		government: "Parliamentary democracy",
		values: [95.9, 1.6, 2.5],
		labels: ["Muslim", "Christian", "Other"],
		population: "31.8 million",
		sources: "(Sources: BBC; CNN; International Christian Concern; Operation World 2010; Release International; The World Factbook 2013; Christian Today; The Times of Israel; Wikipedia. Image Sources: http://sxc.hu and http://flickr.com.)"},
	{name: 'Syria', 
		fullName: "Syrian Arab Republic", 
		description: "Syria's Christian minority have long enjoyed freedom and stability unparalleled in other parts in the Middle East. Traditionally, they have been concentrated in the capital city, Damascus. However, the current civil war has left them and other ethnic and religious minorities particularly vulnerable. Most Christians in Syria are Arab but there is also a large Armenian community.",
		fullDescription: "Syria's Christian minority have long enjoyed freedom and stability unparalleled in other parts in the Middle East. Traditionally, they have been concentrated in the capital city, Damascus. However, the current civil war has left them and other ethnic and religious minorities particularly vulnerable. Most Christians in Syria are Arab but there is also a large Armenian community. <br><br> Christians have traditionally been viewed as loyal to President Assad and consequently face aggression from Islamist rebels. Churches have been attacked and high-profile Christians killed or abducted. There has been a huge exodus of Christians since the outbreak of fighting in 2011; some estimates put the figure at 300,000.",
		capital: "Damascus",
		government: "Republic under an authoritarian regime",
		values: [90, 6.3, 1.4, 2.3],
		labels: ["Muslim", "Christian", "Non-religious", "Other"],
		population: "22.4 million",
		sources: "(Sources: International Christian Concern, Operation World 2010; The Guardian; The World Factbook 2013, VOM Canada; Wikipedia. Image Sources: http://sxc.hu and http://flickr.com.)"
		},
	{name: 'Egypt', 
		fullName: "Arab Republic of Egypt", 
		description: "Egypt has been in transition since February 2011 when a popular uprising forced President Hosni Mubarak to step down and hand power to the military. Subsequent parliamentary elections in November 2011 were dominated by Islamist parties, who won 73 per cent of the seats.",
		fullDescription: "Egypt has been in transition since February 2011 when a popular uprising forced President Hosni Mubarak to step down and hand power to the military. Subsequent parliamentary elections in November 2011 were dominated by Islamist parties, who won 73 per cent of the seats. <br><br> Growing discontent with the Government of President Mohamed Morsi reached a crisis point in July 2013 when the army expelled him and his cabinet from office and installed an interim president. The backlash against Christians by Morsi supporters was immediate. Muslim-background believers feel particularly vulnerable. Yet, tensions between Christians and Muslims were already running high. Violent clashes in and around Cairo in April left ten people dead, with St Mark's Cathedral in the Abbasiya area of the capital a particular flashpoint.",
		capital: "Cairo",
		government: "Transitional",
		values: [86.7, 12.8, 0.5],
		labels: ["Muslim", "Coptic Christian", "Christian"],
		population: "85.2 million",
		sources: "(Sources: BBC; International Christian Concern; Middle East Concern; Operation World 2010; Release International; The World Factbook 2013; Christian Post; Morning Star News; Aid to the Church in Need; CSI, Coptic Foundation for Human Rights; Reuters; Wikipedia. Image Sources: http://sxc.hu and http://flickr.com.)"}
];

var persecutionCities = [
	{ day: 1, name: 'Zhanggongqiao Village, China', geo: '31.613191,120.642946',
		prayerRequest: "Seventeen Christians, including a pastor and his wife, were detained recently after raids on their house church in Zhanggongqiao village, Sichuan province. In the first raid, police and security agents raided a music practice at Langzhong house church and took into custody Pastor Li Min and 15 other church leaders. The group's brass instruments were also confiscated. The next day, a prayer meeting of the same church was raided and the pastor's wife, Song Liangyu, detained. While most of the Christians were released the next day, some were held for a fortnight. Pray for this church and its 1,000-strong membership. Ask God to add to its numbers and bless its leaders with rich fruit in their ministry."},
	{ day: 2, name: 'Beijing, China', geo: '39.90403,116.407526', route: 'car',
		prayerRequest: "Please pray for Christian lawyers in Beijing who have been persecuted for their work in defending religious liberties and other human rights. <a class=\"content_China_2\" href=\"images/content/chi03016_Jiang.JPG\" title=\"Jiang Tianyong\">Jiang Tianyong</a> was detained by the authorities after speaking out about the detention of a fellow Christian lawyer from Beijing, Gao Zhisheng. Jiang was later beaten when he tried to visit another lawyer who had been persecuted. In June 2013, a dozen Beijing law firms known for taking on human rights defence cases did not have their licences renewed by the Beijing Justice Bureau;  Release International partner China Aid described it as 'a targeted move... to neutralise the growing trend of citizens using the law to defend their rights'."},
	{ day: 3, name: 'Alashan, China', geo: '38.851892,105.728969', route: 'car',
		prayerRequest: "The Grace Holy Love (Enhui Shen'ai) House Church in Alashan, Inner Mongolia, was recently ordered to close and cease its 'illegal meetings'. Local officials told the church it had had 'an extremely negative social impact' and its members must join the state-sanctioned Three-Self Church. The move is seen as further proof that the Government is pursuing a 2011 plan to 'abolish house churches in a decade'. Please pray that members of this house church can continue to enjoy fellowship and worship God together. Pray too that the Government's plan to abolish the house church movement will be thwarted."},
	{ day: 4, name: 'Shaya County Prison, China', geo: '43.793028,87.627812',
		prayerRequest: "Pray for justice for Beijing lawyer <a class=\"content_China_4\" href=\"images/content/Gao_Zhisheng.JPG\" title=\"Gao Zhisheng\">Gao Zhisheng</a> who is serving a three-year sentence, passed in 2011, for 'violating the terms of his probation' in Shaya County prison in remote Xinjiang province. Gao was detained in February 2009 and has been held ever since, appearing only briefly in public for little more than a fortnight in 2010. His detention is believed to be linked to his work defending human rights, including religious freedoms. Gao had previously been imprisoned in 2007 when, he alleges, he was tortured. Pray for his wife, Geng He, and his son and daughter, who have fled to the US."},
	{ day: 5, name: 'Zhaskent, Kazakhstan', geo: '44.166667,80', route: 'car',
		prayerRequest: "Pray for justice for seven members of a small Pentecostal church in Zhaskent - four of them in their 60s - who were recently given hefty fines for meeting for worship in a private home. Officers initially accused the group of storing drugs. Church leader Aleksandr Balaev was fined the equivalent of six months of his pension. A 73-year-old woman in the group said she had suffered a heart attack as a result of the raid in which the seven were detained. Thank God for the group's courage. 'They cannot ban me from my Christian faith,' said the 73-year-old."},
	{ day: 6, name: 'Stepnogorsk, Kazakhstan', geo: '52.349722,71.89', route: 'car',
		prayerRequest: "Pray God's protection over Pastor Igor Andreikin and members of New Life Pentecostal Church in Stepnogorsk in the northern Akmola region whom Pastor Igor visited recently. Officials raided the church during his visit, accusing him of conducting 'illegal missionary activity'; this was not long after the church was visited by an official from a state-backed 'anti-sect' centre. Pastor Igor and New Life's pastor, Yevgeni Medvedev, fear that they are also now the subject of officials' attempts to discredit or blackmail them."},
	{ name: 'Zhaskent, Kazakhstan', geo: '44.166667,80'},
	{ day: 7, name: 'Ak-Kya Village, Kyrgyzstan', geo: '41.42482,75.998154', route: 'foot',
		prayerRequest: "Please pray for five Baptists who were beaten up in Ak-Kya village in Ak-Talaa district, central Naryn region, while they distributed gifts to poor schoolchildren, with their teachers' consent. No Christian material was included in the distribution. Police have not brought any serious charges relating to the attack, which they called a 'petty' offence. The impunity with which assailants attacked these believers is symptomatic of the way Christians are discriminated against in Kyrgyzstan. Pray that officials will do more to protect Christians from such attacks. Pray that God will strengthen His people in Kyrgyzstan and embolden them to spread His Word."},
	{ day: 8, name: 'Osh, Kyrgyzstan', geo: '40.523609,72.798973',
		prayerRequest: "Pray for Kyrgyzstan's autocratic President, Almazbek Sharshenovich Atambayev, and his ministers. The Government has been trying further to restrict basic religious rights through recent legislative reform, which it justifies by the threat posed by Islamist extremist group Hizb ut-Tahrir in the south of the country. However, the move is widely viewed as an effort to strengthen the President's grip on power. Pray that Kyrgyzstan's strategic relationship with the US in the global war against terror and its membership of the Organisation for Security and Co-operation in Europe will encourage the Kyrgyz Government to improve its religious rights record."},
	{ day: 9, name: 'Islamabad, Pakistan', geo: '33.718151,73.060547', route: 'car',
		prayerRequest: "Mehrabadi is a poor Christian district near Islamabad where Rimsha Masih, a teenage girl with learning difficulties, was accused of burning verses from the Koran. A court later ruled a Muslim cleric had planted the evidence against her. He justified the action to the police by saying: 'This is the only way to expel Christians from the area.' Dozens of Christian families had to flee. The Supreme Court confirmed Rimsha's innocence. The court ruling is a step in the right direction, but continue to pray for the repeal of the blasphemy laws in Pakistan."},
	{ day: 10, name: 'South Waziristan, Pakistan', geo: '32.320237,69.859741', route: 'direct',
		prayerRequest: "South Waziristan is known as 'al-Qaeda heaven', one of the hotspots in the war against terror in Pakistan. The region is on the frontline, bordering Taliban territory; it's a mountainous region where drone attacks and military strikes are commonplace. Yet, even here, a church meets, welcomed into the army base which has become an enclave for some 200 Christians working to support the military. For two decades, the church had a precarious existence: now it's under the protection of the Pakistan army.  Please pray that the church becomes established, so that even when the soldiers move on, it will continue to be faithful in its witness and flourish under Christ's protection."},
	{ name: 'Islamabad, Pakistan', geo: '33.718151,73.060547'},
	{ day: 11, name: 'Francisabad, Pakistan', geo: '32.095866,74.15776', route: 'car',
		prayerRequest: "Extremists attacked Christians in Francisabad, near Gujranwala in north-east Punjab. A large mob damaged churches, destroyed Christian homes and businesses, and shot four Christians, who survived. They injured 15 others with sticks, including women and children - in the presence of the police. Tensions rose after Muslims objected to music coming from church services. And an argument broke out between a Christian rickshaw driver and Muslim leaders, who accused him of blasphemy. About 3,000 Christian families had to flee. Please pray for peace to be fully restored in Francisabad. Pray that Christians there will trust God, rather than retaliate, and pray for protection for Release partners who are supporting affected Christians."},
	{ day: 12, name: 'Joseph Colony, Pakistan', geo: '31.549722,74.343611',
		prayerRequest: "Please pray for Christians in Joseph Colony, Lahore, whose homes were burnt down after a cry went up that a road sweeper had committed blasphemy. A mob set fire to some 200 Christian houses following accusations that Sawan Masih had insulted Islam during a row with a Muslim. Accusations of blasphemy are often made in Pakistan to settle scores or to justify driving out Christians from areas where they are in a minority. Militants pack the courts to intimidate judges into passing guilty verdicts. Please pray that justice will prevail in Pakistan, and that Christians will be able to live in Joseph Colony without fear of further violence. Pray that Sawan will be acquitted."},
	{ day: 13, name: 'Guriya, India', geo: '25.997625,73.940855',
		prayerRequest: "In March, a mob demolished the small building that is home to the Divya Jyoti Church in Guriya village, Chhattisgarh state, following allegations in the local media that it had been built on government land. Pastor Budhram Baghel maintains that the land belongs to him and that he had permission to build there. The church's opponents are believed to be Hindu nationalists. Local officials and police reportedly stood by as the demolition took place. Pray that this congregation will find a new home and will be fully compensated for this injustice. Pray too that officials such as the police will stop turning a blind eye to such attacks on Christians."},
	{ day: 14, name: 'Kandhamal, India', geo: '20.134204,84.016742', route: 'foot',
		prayerRequest: "Please pray for seven Christians in Odisha state (formerly Orissa), who have been detained since 2008 on suspicion of murdering a Hindu extremist, Swami Lakshmananda Saraswati, in Kandhamal district. His death was the trigger for a campaign of violence across the state, killing 120 Christians, even though Maoist insurgents admitted killing Saraswati. Supporters of the Christian detainees say they are innocent and are being held only to 'appease' extremists. Judges in the so-called 'fast-track courts' set up in the wake of the violence have adjourned the case many times. Many Hindu extremists suspected of involvement in the Odisha attacks have been acquitted, prompting Christian leaders to accuse the authorities of bias and of failing to protect their communities."},
	{ day: 15, name: 'Andhra Pradesh, India', geo: '17.047762,80.098187', route: 'foot',
		prayerRequest: "Pastor Subash was leading a prayer meeting at a private home in Andhra Pradesh with three other Christians when Hindu extremists forced their way in and started punching those present. The extremists threatened to kill the Christians if they returned. The four Christians remain shaken by the attack. Pastor Subash is determined to continue his ministry, despite rising local opposition. Some villages have now barred him from entering. He is one of several pastors in rural areas of Andhra Pradesh to have been attacked this year; Hindu extremists are making determined efforts to increase their influence there. <a class=\"content_India_15\" href=\"images/content/ind4185_India_Hyderabad_protest.JPG\" title=\"Christians protest against the increasing number of attacks against them by Hindu militants\">Christians have protested against the increasing number of attacks against them by Hindu militants</a>. Pray that extremists' efforts to stir up hatred towards Christians will backfire and that the Gospel will spread."},
	{ day: 16, name: 'Moodubelle Village, India', geo: '13.2758,74.824394', route: 'car',
		prayerRequest: "Dozens of Hindu fundamentalists launched a violent attack on Pentecostal Christians in Karnataka state as they prepared for a prayer vigil. Some 30 activists raided Rev Robert Lobo's house in the village of Moodubelle and accused those present of forcibly converting people to Christianity. Eight people were injured and needed hospital treatment; Pastor Ramesh Poojari was said to have suffered serious head wounds. Police reportedly arrived promptly and arrested 16 suspects. Pray that police will keep their promise to seek justice for these Christians. Pray that God will heal and strengthen this congregation, especially those who were injured."},
	{ name: 'Osh, Kyrgyzstan', geo: '40.523609,72.798973'},
	{ day: 17, name: 'Tashkent, Uzbekistan', geo: '40.85,69.6', route: 'foot',
		prayerRequest: "In March officials in the capital Tashkent raided the home of Christians Ashraf and Nargisa Ashurov. The couple were out at the time, having left their children with a babysitter. Officers searched the flat and confiscated Christian materials; in fact, the flat and the confiscated materials belong to a Christian expatriate. Nevertheless, a court imposed huge fines on the Ashurovs and their babysitter, who is a student and a non-Christian - about $3900 each - for crimes including 'organising unauthorised meetings' and 'storing banned materials'. Please pray that the courts will rescind the decision to fine the Ashurovs and their babysitter, and pray that God will protect all three from any further persecution."},
	{ day: 18, name: 'Samarkand, Uzbekistan', geo: '39.657581,66.947601', route: 'foot',
		prayerRequest: "Greater Grace Protestant Church in the central city of Samarkand had to hunt for new premises after it was raided by police officers and secret police in April. The state-registered Baptist church in the city, which is led by Pastor Andrei Kosulitsky, was also given an official warning recently that it was being monitored. Uzbek officials have been quoted as saying that they believe that religious movements are trying to 'destabilise the nation'. Several Protestant churches in different parts of the country have been raided this year. Pray that God will provide premises for congregations without buildings. Pray too that the witness of churches will be strong so that officials see that Christians contribute to social stability and unity."},
	{ day: 19, name: 'Dushanbe, Tajikistan', geo: '38.536667,68.78', route: 'direct',
		prayerRequest: "Please pray for Christians in Tajikistan where religious liberties are increasingly restricted. The law does not permit any preaching or teaching of Christian doctrine in schools, residential buildings or homes. No Tajik is allowed to go abroad for religious education unless they have already had such education from a state-authorised institution at home - yet there are no such approved seminaries or Bible colleges in Tajikistan. Fines for violating religious laws were raised to exorbitant levels last year. Pray that the Holy Spirit will teach and guide Tajik Christians, filling them with wisdom."},
	{ day: 20, name: 'Kabul, Afghanistan', geo: '34.528455,69.171703', route: 'direct',
		prayerRequest: "Christians in Afghanistan face an uncertain future, with the withdrawal of coalition troops in 2014 drawing ever closer. The pressure on Christians remains intense and many pay a huge price for following Christ. Afghan Christians <a class=\"content_Afghanistan_20\" href=\"images/content/Said_Musa_2877281847_afghanistan.JPG\" title=\"Said Musa\">Said Musa</a> and Shoaib Assadullah, both of whom were charged with apostasy for converting from Islam, had to seek asylum abroad to guarantee their safety. Yet, the Afghan church is reported to be growing in number and maturity. Pray that the political climate will change to allow greater religious liberty. Ask God to fill His people in Afghanistan with His perfect peace."},
	{ name: 'Samarkand, Uzbekistan', geo: '39.657581,66.947601'},
	{ day: 21, name: 'Dashoguz City, Turkmenistan', geo: '41.834461,59.957321', route: 'foot',
		prayerRequest: "There has been a considerable upsurge in the number of raids on Christian homes and gatherings in Turkmenistan during the past 12 months - and an increase in the number of Christians being fined in relation to religious activities. For example, 11 Baptists in the northern city of Dashoguz were each fined two months' average wages for 'participating in an unregistered religious community', a week after their Sunday worship meeting was raided. One of the 11 Baptists was a 17-year-old student. The Christians are reported to have been paying these fines in instalments. Pray that God will provide for these 11 Christians and cause them to prosper. Pray that their faith will be strengthened by this ordeal."},
	{ day: 22, name: 'Turkmenbashi, Turkmenistan', geo: '40.025051,52.957569', route: 'direct',
		prayerRequest: "The Baptist House of Prayer in Turkmenbashi, formerly known as Kranovodsk, was burned to the ground in 2012 by unknown assailants. Members of the church are suspicious of the authorities' response to the blaze, which was to summon for questioning Vasily Korobov, President of the Turkmen Baptist Union. Harassment of Christians has intensified since mid-2012. Almost every expatriate Christian has been expelled and several native Christians have been given stiff fines for participating in unregistered religious communities. Several pastors have been exiled, beaten, heavily fined or imprisoned. Pray that every Christian in Turkmenistan will know that God is their refuge and their strength."},
	{ day: 27, name: 'Tehran, Iran', geo: '35.696216,51.422945', route: 'car',
		prayerRequest: "Tehran is home to Iran's Evin Prison where several Christians are currently being held. These include Pastor <a class=\"content_Iran_27\" href=\"images/content/saeed_ABEDINI.JPG\" title=\"Saeed Abedini\">Saeed Abedini</a>, who is serving an eight-year sentence due to his work with Iranian house fellowships. Pastor Saeed has been denied adequate medical treatment and was held in solitary confinement for a time after protesting about conditions in the jail. Several other pastors are currently detained in Iran, including Behnam Irani who has been held in Karaj Ghezal Hesar prison since May 2011. He is serving a total of six years for alleged crimes against 'national security'. His health has suffered severely due to abuse in custody and he has had no treatment. Pray for all Christians currently detained in Iran: Release is aware of at least 20."},
	{ day: 26, name: 'Rasht, Iran', geo: '37.280833,49.583056', route: 'direct',
		prayerRequest: "Pray that God will equip, and be close to, all those currently in prison because of their witness for Christ."},
	{ day: 25, name: 'Aliabad, Azerbaijan', geo: '38.841157,48.443162', route: 'direct',
		prayerRequest: "Pastor <a class=\"content_Azerbaijan_25\" href=\"images/content/Zaur_Balayev_040_.JPG\" title=\"Zaur Balayev\">Zaur Balayev</a> and church worker Hinayat Shabanova, who live and serve in Aliabad village, in Zaqataly region, were each given a stiff fine of 1,500 manats ($1880) by a court in April 2013, apparently for holding worship services. Thank God that their fines were dropped on appeal. Yet, the pair were threatened with even tougher penalties unless they stopped their Christian activities. Pray God's protection over these two Christians, their families and congregations. Pray particularly for Pastor Balayev's wife, who has pancreatic cancer: pray that she will receive the medical treatment she needs and that God will ensure her healing is complete."},
	{ day: 24, name: 'Baku, Azerbaijan', geo: '40.43495,49.867623', route: 'direct',
		prayerRequest: "Greater Grace Church in Azerbaijan's capital city, <a class=\"content_Azerbaijan_24\" href=\"images/content/P1040273_azerbaijan.JPG\" title=\"Capital Baku\">Baku</a>, is fighting a long legal battle to resist a court order that it should be liquidated. A court ordered the church closure last year - and Greater Grace lost its appeal, which means that any further religious activity there is now illegal. However, Greater Grace has vowed to fight the decision all the way to the European Court.  This was the first known closure of a religious community in Azerbaijan under the controversial Law on Freedom of Religion passed in 2009. The law required all religious communities to re-register - including those like Greater Grace which had registered before. Christians fear the case may set a worrying precedent for other churches. Pray that Greater Grace will be allowed to continue its ministry in Baku. Pray that the Holy Spirit will sustain its congregation in the meantime."},
	{ day: 23, name: 'Sumgayit, Azerbaijan', geo: '40.589722,49.668611', route: 'direct',
		prayerRequest: "Last September, members of the Byakov family were stopped at the border crossing at Yalama in Khachmaz district on Azerbaijan's northern border as they returned in their minibus from Russia. Officers seized a large quantity of Christian literature and confiscated Pyotr Byakov's passport and the bus. The family, who are Baptists from Sumgayit, were told the literature was to be scrutinised by the state body which operates Azerbaijan's religious censorship. Azerbaijan exercises strict controls over religious literature and materials are often confiscated in raids on religious meetings and at the border. Pray that the authorities will relax these restrictions in the interests of religious freedom. Ask God to protect the Byakov family too."},
	{ name: 'Tehran, Iran', geo: '35.696216,51.422945'},
	{ day: 28, name: 'Ahvaz, Iran', geo: '31.31671,48.68438', route: 'foot',
		prayerRequest: "Please pray for a pastor, his wife and two other Christians from Ahvaz who are serving a one-year jail sentence for turning to Christ. Pastor Farhad, his wife Shahnaz and two members of their church, Davoud and Naser, recently lost their appeal at the High Court against a conviction last October. They had been found guilty of 'converting to Christianity, inviting Muslims to convert, and propagating against the Islamic regime through promoting Evangelical Christianity'. They were first detained in December 2011 during a raid on their officially recognised Assemblies of God church, which has remained closed ever since. Pray that God will help Pastor Farhad's congregation find ways to continue in fellowship and provide an inspiring leader for them during Farhad's absence."},
	{ day: 29, name: 'Baghdad, Iraq', geo: '33.325,44.422', route: 'car',
		prayerRequest: "Please pray for <a class=\"content_Iraq_29\" href=\"images/content/Canon-Andrew-White-3.JPG\" title=\"Canon Andrew White\">Canon Andrew White</a> and the congregation at St George's Church in Baghdad. Canon Andrew, a Release partner, is said to be one of the few remaining British expatriates in Baghdad. His church leadership have all been killed, he says - and most of the Christians with a Muslim background in his church have been killed too. He lives under constant armed guard, in a fortified compound. Yet, he remains steadfast, ministering to Christians and Muslims alike. Thank God for Canon Andrew's remarkable witness and courage. Pray God's protection over him and his congregation. Pray that his church will thrive and grow."},
	{ day: 30, name: 'Mosul, Iraq', geo: '36.34,43.13', route: 'foot',
		prayerRequest: "A Christian in Mosul was the target of two bomb attacks in one week earlier this year. The first bomb exploded inside his house on one day; a second one was thrown over his fence four days later and had to be defused by military engineers. Such attacks are frequent. Adbuljabar Khidher Toza, another Christian from Mosul, was shot dead at home in April. Islamist extremists want Iraq to be rid of Christians and some of their violence is specifically targeted at this minority. Many Christians have fled Iraq as a consequence; others who remain in the country say they feel forgotten and alone. Pray that the Government will do more to protect this shrinking minority."},
	{ day: 31, name: 'Aleppo, Syria', geo: '36.215549,37.159279', route: 'car',
		prayerRequest: "Two Orthodox bishops have not been seen since they were kidnapped in Aleppo in late-April as they returned from a humanitarian mission in Turkey. There is deep concern for Archbishop Yohanna Ibrahim and Bishop Boulos Yazigi. Their abduction has been a focus for Christians' fears about mounting persecution targeting their community. Pray that the two bishops will be released unharmed and returned home soon. Pray also that the church in Syria will be blessed with strong leadership during this difficult time."},
	{ day: 32, name: 'Damascus, Syria', geo: '33.5111,36.3064', route: 'direct',
		prayerRequest: "Syria's Christians are caught in the crossfire in the ongoing civil war - and increasingly are a target for violence themselves. The Sunni rebels locked in combat with President Assad's troops have the backing of radical Islamist groups, some with links to al-Qaeda, who appear to have Christians in their sights too. Until the current conflict, Syria's Christians were well integrated into society: the Christian communities in Syria are among the oldest in the world. Pray that God's presence will be very real to His people in Syria. Pray that, as St Paul met God on the road to Damascus, so many more will turn to Christ in Syria."},
	{ day: 33, name: 'Cairo, Egypt', geo: '30.04841,31.236199', route: 'foot',
		prayerRequest: "Christians in Egypt feel increasingly at risk as religious persecution increases amid the political turmoil. The overthrow of President Morsi led to an immediate backlash against Christians by his supporters: Christians were threatened publicly and accused of complicity in Morsi’s expulsion, along with ‘secularists’ and the military. Anti-Christian violence was reported in several areas; police had to warn church leaders in Cairo and its surrounds to be on the lookout for cars with certain number plates, amid warnings of car bombs. Please pray God’s peace over Christians in the Egyptian capital and beyond. Pray that He will be close to the congregation of St Mark's Cathedral in the Abbasiya area of Cairo, the scene of violent clashes in April which left two dead and more than 90 injured. Pray that calm and unity will be restored, and pray that Christians will lead the way in promoting reconciliation."},
	{ day: 34, name: 'Menbal Village, Egypt', geo: '28.408919,30.68141', route:'foot',
		prayerRequest: "A mob attacked Christian businesses and shops in Menbal village in Minya province in May, leaving several people injured and some properties badly damaged. Christians said they were verbally abused and threatened, and told to leave the village. Then, in July, immediately after Morsi’s overthrow, his supporters attacked Al Eslah Church and St George’s Church in Delgia village, also in Minya, as well as Christian properties in the area. One minister narrowly escaped with his life when rioters set light to his church: Muslim neighbours hid him from the mob. Pray that the moderate majority in Egypt will speak out against extremism and that their voice will be heeded."},
	{ day: 35, name: 'Luxor, Egypt', geo: '25.683333, 32.65', route: 'direct',
		prayerRequest: "Hard-line Muslims in Egypt angry over President Morsi’s expulsion immediately turned on churches and Christian property, accusing Christians of complicity. Worst hit was Naga Hassan village, west of Luxor, where rioting, reportedly triggered by a row between a Muslim and a Christian, resulted in the death of four Christians and the destruction of dozens of homes. Police reportedly asked Christians in the village to leave their homes until peace was restored. Pray for wisdom for Supreme Constitutional Court Chief Justice Adly Mansour, who was sworn in as Egypt’s interim president in July. Pray that all Egyptian citizens, politicians and electorate alike, will choose peace."}
];

var totalNumberDays = 1;
for (i = 0; i< persecutionCities.length; i++) {
	// assumes ordered array...
	if (typeof persecutionCities[i].day != "undefined") totalNumberDays = persecutionCities[i].day;
}

jQuery.browser={};(function(){jQuery.browser.msie=false;
jQuery.browser.version=0;if(navigator.userAgent.match(/MSIE ([0-9]+)\./)){
jQuery.browser.msie=true;jQuery.browser.version=RegExp.$1;}})();

initMap();